package com.boot.proxyip.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.boot.proxyip.entity.ProxyIp;

public interface ProxyIpMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	int insert(ProxyIp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	int insertSelective(ProxyIp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	ProxyIp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	int updateByPrimaryKeySelective(ProxyIp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table proxy_ip
	 *
	 * @mbg.generated Fri Sep 01 16:56:17 CST 2017
	 */
	int updateByPrimaryKey(ProxyIp record);

	ProxyIp queryByIpAndPort(@Param("ip") String ip, @Param("port") Integer port);

	List<ProxyIp> queryAll();

	int modifyValid(@Param("valid") boolean b,@Param("id") int id);
}